[package]
name = "cve-2012-2982"
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["0xTas <root@0xtas.dev>"]
repository = "https://github.com/0xTas/CVE-2012-2982"
description = "A PoC exploit for CVE-2012-2982 implemented in Rust"


[profile.release]
lto = true
strip = true


[dependencies]
rand = "0.8.5"
clap = { version = "4.0.18", features = ["derive"] }
reqwest = { version = "0.11.12", features = ["blocking"] }
